POST http://localhost:8080
RemoteUrl: http://localhost:8090/remote.php/dav/files/test/sample.jpg
Authorization: Basic dGVzdDp0ZXN0
Content-Type: application/json

{
    "type": "Flagged",
    "flagged": true
}
